-- Existing website migration. No posts, subscribers, or experience are deleted.
-- Replace YOUR_ADMIN_EMAIL below with the email you use to sign in to admin.
-- Run this entire file in Supabase SQL Editor as the database owner.
begin;
create table if not exists public.portfolio_admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.portfolio_admins enable row level security;
do $$
declare chosen uuid;
begin
  select id into chosen from auth.users where lower(email)=lower('YOUR_ADMIN_EMAIL');
  if chosen is null then raise exception 'Replace YOUR_ADMIN_EMAIL with your existing admin login email before running this migration.'; end if;
  insert into public.portfolio_admins(user_id) values(chosen) on conflict do nothing;
end $$;
create or replace function public.is_portfolio_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.portfolio_admins where user_id=auth.uid()); $$;
revoke all on function public.is_portfolio_admin() from public;
grant execute on function public.is_portfolio_admin() to anon, authenticated;
drop policy if exists own_admin_membership on public.portfolio_admins;
create policy own_admin_membership on public.portfolio_admins for select to authenticated using(user_id=auth.uid());
grant select on public.portfolio_admins to authenticated;

alter table public.posts add column if not exists featured boolean not null default false;
alter table public.posts add column if not exists parent_post_id bigint references public.posts(id) on delete cascade;
create index if not exists posts_parent_post_id_idx on public.posts(parent_post_id);

create table if not exists public.notebook_projects (
 id text primary key default gen_random_uuid()::text,
 title text not null check(char_length(title) between 1 and 240),
 summary text not null default '' check(char_length(summary)<=240),
 kind text not null default 'Building' check(kind in ('Building','Research','Product','Learning','Personal')),
 status text not null default 'planned' check(status in ('planned','building','shipped','paused','dropped')),
 current text not null default '' check(char_length(current)<=4000),
 thinking text not null default '' check(char_length(thinking)<=4000),
 next_step text not null default '' check(char_length(next_step)<=4000),
 url text not null default '' check(url='' or url ~ '^https?://'),
 thread_url text not null default '' check(thread_url='' or thread_url ~ '^https?://' or thread_url ~ '^/[^/]'),
 start_date date, progress integer check(progress between 0 and 30),
 pinned boolean not null default false, sort_order integer not null default 0,
 updated_at timestamptz not null default now()
);
create table if not exists public.notebook_entries (
 id bigint generated by default as identity primary key,
 project_id text not null references public.notebook_projects(id) on delete cascade,
 title text not null check(char_length(title) between 1 and 240),
 body text not null check(char_length(body) between 1 and 4000),
 url text not null default '' check(url='' or url ~ '^https?://'),
 published boolean not null default false, created_at timestamptz not null default now()
);
alter table public.notebook_entries add column if not exists sprint_day integer check(sprint_day between 1 and 30);
create index if not exists notebook_entries_project_date on public.notebook_entries(project_id,created_at desc);
alter table public.notebook_projects enable row level security;
alter table public.notebook_entries enable row level security;
drop policy if exists notebook_read on public.notebook_projects;
create policy notebook_read on public.notebook_projects for select using(true);
drop policy if exists notebook_admin on public.notebook_projects;
create policy notebook_admin on public.notebook_projects for all to authenticated using(public.is_portfolio_admin()) with check(public.is_portfolio_admin());
drop policy if exists notebook_entry_read on public.notebook_entries;
create policy notebook_entry_read on public.notebook_entries for select using(published or public.is_portfolio_admin());
drop policy if exists notebook_entry_admin on public.notebook_entries;
create policy notebook_entry_admin on public.notebook_entries for all to authenticated using(public.is_portfolio_admin()) with check(public.is_portfolio_admin());
grant select on public.notebook_projects, public.notebook_entries to anon;
grant select,insert,update,delete on public.notebook_projects, public.notebook_entries to authenticated;
grant usage,select on sequence public.notebook_entries_id_seq to authenticated;

create or replace function public.notebook_project_guard() returns trigger
language plpgsql set search_path=public as $$
begin
 perform pg_advisory_xact_lock(814510);
 if new.status in ('paused','dropped') then new.pinned=false; end if;
 if new.pinned and (select count(*) from public.notebook_projects where pinned and id<>new.id)>=5 then
   raise exception 'Your desk holds five chapters. Unpin another chapter first.';
 end if;
 new.updated_at=now(); return new;
end $$;
drop trigger if exists notebook_project_guard on public.notebook_projects;
create trigger notebook_project_guard before insert or update on public.notebook_projects for each row execute function public.notebook_project_guard();

-- Some installations never created the experience table.
do $$ begin
if to_regclass('public.experience') is null then
  create table public.experience (
    id bigserial primary key, date_range text not null, role text not null,
    org text not null, description text default '', sort_order integer default 0,
    created_at timestamptz default now()
  );
  insert into public.experience(date_range,role,org,description,sort_order) values
('2025 – Present','Research Intern','IVCCE — Indorama Ventures Center for Clean Energy, Plaksha','Working on a smart nudging system to reduce household energy consumption. Researching how data-driven behavioural interventions can create measurable impact at scale — without requiring users to change habits by willpower alone. Also led outreach for the IVCCE Energy Conference, building sponsor and participant pipelines across student, academic, and industry networks.',0),
('2024 – 2025','Outreach & Events Leadership','Plaksha University · Fitoor, Eklavya & IVCCE Energy Conference','Drove outreach for Fitoor, Eklavya, and the IVCCE Energy Conference, serving as Outreach Head for Eklavya and the Energy Conference. Across the three events, our teams reached 1,500+ people and brought in 800+ participants — experience that sharpened my communication, stakeholder mapping, follow-up discipline, and ability to turn interest into attendance.',1),
('2025','Management Fellow — YTS Program','Plaksha University','Worked as a management fellow for the Young Technology Scholar program at Plaksha. Helped coordinate and run the program, developing skills in team management, communication, and institutional operations alongside technical studies.',2),
('2024 – Present','B.Tech Engineering Student','Plaksha University, Chandigarh','Second-year engineering student focused on applying CS and AI to real-world systems. Building IoT projects, learning ML algorithms independently, and seeking every opportunity to apply theory to practice.',3);
end if;
end $$;
alter table public.experience enable row level security;
drop policy if exists public_read_experience on public.experience;
create policy public_read_experience on public.experience for select using(true);
drop policy if exists experience_owner on public.experience;
create policy experience_owner on public.experience for all to authenticated using(public.is_portfolio_admin()) with check(public.is_portfolio_admin());
grant select on public.experience to anon;
grant select,insert,update,delete on public.experience to authenticated;
grant usage,select on sequence public.experience_id_seq to authenticated;

-- Restrictive policies also constrain any older broad authenticated policies.
do $$
declare t text; operation text;
begin
 foreach t in array array['posts','experience','comments','subscribers','settings'] loop
   execute format('alter table public.%I enable row level security',t);
   foreach operation in array array['insert','update','delete'] loop
     execute format('drop policy if exists %I on public.%I','owner_'||operation,t);
     if operation='insert' and t in ('comments','subscribers') then continue; end if;
     if operation='insert' then
       execute format('create policy owner_insert on public.%I as restrictive for insert to anon,authenticated with check(public.is_portfolio_admin())',t);
     elsif operation='update' then
       execute format('create policy owner_update on public.%I as restrictive for update to anon,authenticated using(public.is_portfolio_admin()) with check(public.is_portfolio_admin())',t);
     else
       execute format('create policy owner_delete on public.%I as restrictive for delete to anon,authenticated using(public.is_portfolio_admin())',t);
     end if;
   end loop;
 end loop;
end $$;
drop policy if exists owner_read on public.subscribers;
create policy owner_read on public.subscribers as restrictive for select using(public.is_portfolio_admin());
drop policy if exists owner_read on public.settings;
create policy owner_read on public.settings as restrictive for select using(public.is_portfolio_admin());
drop policy if exists owner_read_comments on public.comments;
create policy owner_read_comments on public.comments for select to authenticated using(public.is_portfolio_admin());
drop policy if exists safe_public_comment on public.comments;
create policy safe_public_comment on public.comments as restrictive for insert with check(
 approved=false and char_length(name) between 1 and 60 and char_length(message) between 3 and 1000
);
alter view public.post_stats set (security_invoker=true);

-- Hide visitor tokens. Anonymous clients use narrow like RPCs instead.
drop policy if exists likes_private on public.likes;
create policy likes_private on public.likes as restrictive for all using(public.is_portfolio_admin()) with check(public.is_portfolio_admin());
create or replace function public.portfolio_like_state(p_post_id bigint,p_token text) returns jsonb
language sql security definer set search_path=public as $$
 select jsonb_build_object('count',(select count(*) from public.likes where post_id=p_post_id),'liked',exists(select 1 from public.likes where post_id=p_post_id and fingerprint=p_token));
$$;
create or replace function public.portfolio_set_like(p_post_id bigint,p_token text,p_liked boolean) returns jsonb
language plpgsql security definer set search_path=public as $$
begin
 if char_length(p_token)<20 or char_length(p_token)>128 then raise exception 'Invalid visitor token'; end if;
 if p_liked then insert into public.likes(post_id,fingerprint) values(p_post_id,p_token) on conflict(post_id,fingerprint) do nothing;
 else delete from public.likes where post_id=p_post_id and fingerprint=p_token; end if;
 return public.portfolio_like_state(p_post_id,p_token);
end $$;
revoke all on function public.portfolio_like_state(bigint,text),public.portfolio_set_like(bigint,text,boolean) from public;
grant execute on function public.portfolio_like_state(bigint,text),public.portfolio_set_like(bigint,text,boolean) to anon,authenticated;

alter table public.subscribers add column if not exists unsubscribe_token uuid not null default gen_random_uuid();
alter table public.subscribers add column if not exists unsubscribed boolean not null default false;
create unique index if not exists subscriber_unsubscribe_token on public.subscribers(unsubscribe_token);
drop policy if exists safe_subscriber on public.subscribers;
create policy safe_subscriber on public.subscribers as restrictive for insert with check(
 char_length(email) between 3 and 254 and email ~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' and unsubscribed=false
);
create or replace function public.portfolio_unsubscribe(p_token uuid) returns void
language sql security definer set search_path=public as $$
 update public.subscribers set unsubscribed=true where unsubscribe_token=p_token;
$$;
revoke all on function public.portfolio_unsubscribe(uuid) from public;
grant execute on function public.portfolio_unsubscribe(uuid) to anon,authenticated;
create table if not exists public.newsletter_deliveries (
 post_id bigint references public.posts(id) on delete cascade,
 subscriber_id bigint references public.subscribers(id) on delete cascade,
 sent_at timestamptz not null default now(), primary key(post_id,subscriber_id)
);
alter table public.newsletter_deliveries enable row level security;
drop policy if exists delivery_owner on public.newsletter_deliveries;
create policy delivery_owner on public.newsletter_deliveries for all to authenticated using(public.is_portfolio_admin()) with check(public.is_portfolio_admin());
grant select,insert on public.newsletter_deliveries to authenticated;

-- Seed once. Reruns neither overwrite edits nor recreate deleted chapters.
create table if not exists public.portfolio_migrations(version text primary key);
alter table public.portfolio_migrations enable row level security;
do $$ begin
if not exists(select 1 from public.portfolio_migrations where version='notebook-v1') then
insert into public.notebook_projects(id,title,kind,status,summary,current,thinking,next_step,url,thread_url,start_date,progress,pinned,sort_order) values
('spin-sync','Spin Sync','Building','building','Making shared laundry a little less chaotic.','An IoT laundry project with a scheduling dashboard.','','','','',null,null,true,0),
('energy-nudging','Smarter energy habits','Research','building','Researching smart energy nudges with IVCCE.','Exploring how data and timely nudges can help reduce energy consumption.','','','','/blog/post.html?slug=energy-nudges-research-notes',null,null,true,1),
('outreach-brain','Outreach Brain','Product','shipped','A CRM born from an outreach problem I faced.','One shared space for contacts, WhatsApp outreach, follow-ups and registrations.','Built in response to the difficulty of managing outreach across scattered spreadsheets.','','https://outreach-brain.aliass.workers.dev/','',null,null,true,2),
('ml-sprint','30 days of ML','Learning','planned','A learning sprint, documented as one evolving thread.','Starting on 5 September 2026. No days completed yet.','','Start the sprint and write the opening blog post.','','','2026-09-05',0,true,3),
('this-site','This little corner','Personal','building','An active copy of my brain, always in progress.','Turning this site into a place to share what I build, learn and think.','I want friends, family, collaborators and readers to see the person behind the projects.','Keep adding honest notes as the work changes.','','',null,null,true,4)
on conflict(id) do nothing;
insert into public.portfolio_migrations(version) values('notebook-v1');
end if;
end $$;
commit;
