-- The old schema reset deleted live posts and subscribers.
-- For this existing website, use notebook-migration.sql instead.
-- Replace YOUR_ADMIN_EMAIL there and run the whole migration.
-- Do not run an old copy of this file against the production database.
